---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Campione.
--- DateTime: 2025/4/7 10:24
---

-- 获取参数
local accessTokenKey = KEYS[1]
local refreshTokenKey = KEYS[2]
local userId = ARGV[1]
local accessTokenExpire = tonumber(ARGV[2])
local refreshTokenExpire = tonumber(ARGV[3])

-- 设置访问令牌
redis.call('SET', accessTokenKey, userId, 'PX', accessTokenExpire)

-- 设置刷新令牌
redis.call('SET', refreshTokenKey, userId, 'PX', refreshTokenExpire)

return 1
