server:
  port: 8083
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/zh-goods?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  root
    password:  XHJ040714+
    hikari:
      # 连接池核心配置（解决 "Too many connections" 关键参数）
      maximum-pool-size: 5          # 最大连接数（建议≤数据库max_connections的80%，假设数据库max_connections=150，则设为120）
      minimum-idle: 2                # 最小空闲连接数（根据基础并发量调整）
      connection-timeout: 30000        # 连接超时时间（30秒，避免长时间等待无效连接）
      connection-test-query: SELECT 1  # 测试连接有效性的SQL（必填，避免获取无效连接）
      idle-timeout: 600000            # 空闲连接存活时间（10分钟，及时释放空闲连接）
      max-lifetime: 1800000           # 连接最大存活时间（30分钟，防止连接老化）
  application:
    name: goods-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos      # 加上
      password: nacos      # 加上（默认就是 nacos/nacos）
  redis:
    host: localhost
    port: 6379
#    password:
